name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your repository's code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Set Python version, adjust to match your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from your requirements.txt

      - name: Run tests
        run: |
          pytest  # Run your tests (you can change this if you're using a different test framework)
