name: YOLOv8 Inference Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-ai-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ultralytics Pillow PyYAML

    - name: Download model from GitHub Releases
      run: |
        curl -L -o best.pt https://github.com/zjohn11/YOLO_ObjectDetection/releases/download/v1.0.0/best.pt

    - name: Run test script
      run: python test.py
