name: CI Workflow

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download model from GitHub Releases
        run: |
          curl -L -o best.pt https://github.com/zjohn11/YOLO_ObjectDetection/releases/download/v1.0.0/best.pt

      - name: Unzip dataset
        run: unzip yolo_dataset.zip -d yolo_dataset

      - name: Run testing script
        run: python test.py
